[mkdocs]
title = "MkDocs"
favicon = "ðŸ“˜"
nav = [
    {title="Introduction", path="index.md"},
    {title="Writing Markdown", path="writing.md"},
    {title="Site Navigation", path="navigation.md"},
    {title="HTML Styling", path="styling.md"}
]
