[mkdocs]
nav = [
    {title="Introduction", path="index.md"},
    {title="Writing Markdown", path="writing.md"},
    {title="Interlinking & Navigation", path="navigation.md"},
    {title="HTML Styling", path="styling.md"},
    {title="Roadmap", path="roadmap.md"}
]
loaders = [
    {type="package", pkg="mkdocs:theme"},
    {type="directory", dir="docs"},
]

[context]
title = "MkDocs"
favicon = "ðŸ“˜"
