[mkdocs]
nav = [
    {title="Introduction", path="index.md"},
    {title="Writing Markdown", path="writing.md"},
    {title="Interlinking & Navigation", path="navigation.md"},
    {title="Themes & Styling", path="styling.md"}
]

[loaders]
theme = "pkg://mkdocs/default"
docs = "dir://docs"

[context]
title = "MkDocs"
favicon = "ðŸ“˜"
