[mkdocs]
title = "MkDocs"
favicon = "ðŸ“˜"
nav = [
    {title="Introduction", path="index.md"},
    {title="Writing Markdown", path="writing.md"},
    {title="Interlinking & Navigation", path="navigation.md"},
    {title="HTML Styling", path="styling.md"}
]

#Â [context]
# site_title = "MkDocs"
# site_description = "..."
# site_favicon = "ðŸ“˜"
